name: turtle-test

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs: 
  turtle-docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses apache
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="jleekwong/apache"
          source .github/workflows/utils.sh
          alpine_arm_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm")
